package com.example.hariharasudhan.glassfirst;

import android.app.Activity;
import android.content.Context;
import android.media.AudioManager;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;

import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollView;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;





/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class ResultActivity extends Activity {

    /** {@link CardScrollView} to use as the main content view. */
    private CardScrollView mCardScroller;

    /** "Hello World!" {@link View} generated by {@link #buildView()}. */
    private View mView;

    public static final String SEARCH = "search";
    private String mPlatform="Android";
    private List<CardBuilder> mCards;
    HashMap eventDetails;
    private String platform;

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        if(getIntent().hasExtra(SEARCH)){
            platform = getIntent().getStringExtra(SEARCH);
        }

        if(platform.equals("Glass")){
            buildGlass();
        }else if (platform.equals("Javascript")){
            buildJavascript();
        }else{
            buildRuby();
        }

        Log.d("EVENT",platform);

        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(new com.example.hariharasudhan.glassfirst.EventAdapter(mCards));
        // Handle the TAP event.
        mCardScroller.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Plays disallowed sound to indicate that TAP actions are not supported.
                AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                am.playSoundEffect(Sounds.DISALLOWED);
            }
        });
        setContentView(mCardScroller);
    }

    @Override
    protected void onResume() {
        super.onResume();
        mCardScroller.activate();
    }

    @Override
    protected void onPause() {
        mCardScroller.deactivate();
        super.onPause();
    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.
     */
    private void buildJavascript() {
        mCards = new ArrayList<CardBuilder>();

        mCards.add(new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                .setText("An independent meeting on building cutting-edge web and Node.js applications, hosted by Manning Publications.")
                .setIcon(R.drawable.javascript)
                .setHeading("Powered by JavaScript")
                .setSubheading("St. Louis, United States")
                .setFootnote("Javascript")
                .setTimestamp("17 September 2014"));

        mCards.add(new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                .setText("Cutting-edge workshops JavaScript to AngularJS, JavaScript Security, Web Application Architecture")
                .setIcon(R.drawable.javascript)
                .setHeading("JavaScript Days 2014")
                .setSubheading("Berlin, Germany")
                .setFootnote("Javascript")
                .setTimestamp("13 October 2014"));

        mCards.add(new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                .setText("Learn how to enhance your JavaScript skills to make your projects smoother, more lightweight, and incredibly interactive.")
                .setIcon(R.drawable.javascript)
                .setHeading("Future of Web Apps")
                .setSubheading("Boston, United States")
                .setFootnote("Javascript")
                .setTimestamp("27 October 2014"));
    }

    private void buildRuby() {
        mCards = new ArrayList<CardBuilder>();

        mCards.add(new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                .setText("A conference surrounded by history.")
                .setIcon(R.drawable.rails)
                .setHeading("RubyConf Portugal")
                .setSubheading("St. Louis, United States")
                .setFootnote("Ruby")
                .setTimestamp("13 October 2014"));

        mCards.add(new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                .setText("The largest Ruby event in the Spanish speaking world")
                .setIcon(R.drawable.rails)
                .setHeading("Ruby Conf 2014")
                .setSubheading("Buenos Aires, Argentina")
                .setFootnote("Ruby")
                .setTimestamp("13 October 2014"));

        mCards.add(new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                .setText("Learn how to enhance your Ruby skills to make your projects smoother, more lightweight, and incredibly interactive.")
                .setIcon(R.drawable.rails)
                .setHeading("Barcelona Ruby Conference")
                .setSubheading("Barcelona, Spain")
                .setFootnote("Ruby")
                .setTimestamp("27 October 2014"));
    }

    private void buildGlass() {
        mCards = new ArrayList<CardBuilder>();

        mCards.add(new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                .setText("Workshop on the functionality of the Google Glass, and also talk to developers about the possibilities and limitations of the device.")
                .setIcon(R.drawable.ic_glass_logo)
                .setHeading("Workshop : On Google Glass")
                .setSubheading("Chennai, India")
                .setFootnote("Google Glass")
                .setTimestamp("just now"));

        mCards.add(new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                .setText("When Glass is ready….will you be?")
                .setIcon(R.drawable.ic_glass_logo)
                .setHeading("GGDevCon : Google Glass developer conference")
                .setSubheading("Burlingame, United States")
                .setFootnote("Google Glass")
                .setTimestamp("27 October 2014"));
    }

}
